library(readxl)   
library(tm)       
library(cluster)
excel_data <- read_excel("E:/problems.xlsx")
print(excel_data)
corpus <- Corpus(VectorSource(excel_data$grievances))
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("en")) 
corpus <- tm_map(corpus, stripWhitespace)
dtm <- DocumentTermMatrix(corpus)
distance_matrix <- dist(as.matrix(dtm))
hierarchical_clusters <- hclust(distance_matrix, method = "ward.D")
plot(hierarchical_clusters)